const projects = {
    cambolink: {
        title: 'Cambolink',
        description: '셀러별 공동구매 페이지를 제공하는 셀러 전용 공동구매 플랫폼',
        features: [
            '셀러별 개인 공동구매 페이지 제공',
            '상품 등록 및 홍보 링크 생성',
            '공동구매',
            '구매자 신청 리스트 다운로드',
            '셀러전용 유료플랜 결제 및 상품슬롯 확장'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'Recoil',
            'Fastify',
            'Node.js',
            'Knex.js',
            'AWS Lambda',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-03 - 2024-06',
        contribution: [
            '개발인원 3명 중 1명으로 풀스택 개발 참여',
            '',
            '프론트엔드/백엔드 아키텍처 설계 참여',
            '  - 멀티 테넌트 아키텍처: Next.js 동적 라우팅 기반 사용자별 페이지 시스템 설계',
            '  - 서버리스 백엔드: AWS Lambda + Fastify 기반 API 아키텍처 구축',
            '프론트엔드/백엔드 5개 주요 기능 · 로직 개발 (35%)',
            '  - 셀러 페이지 관리 기능 (페이지 할당, 동적 라우팅, SEO 최적화, 커스터마이징)',
            '  - 제품 등록 및 관리 기능',
            '  - 공동구매 구매',
            '  - 프로필 및 셀러 페이지 커스터마이즈 기능',
            '라이브 서비스 운영 전담',
        ],
        totalDeveloper: 3,
        contributedPercentage: 40,
        frontEnd: true,
        backend: true,
        detail: [
            '### 서버리스 아키텍처 설계 및 구현',
            'Next.js / Fastify로 구성된 풀스택 프로젝트를 AWS Lambda 서버리스 환경으로 구성. ',
            '### 동적 SEO 최적화 시스템 구축',
            '각 셀러의 pageLink별로 검색 엔진에 개별 노출되어야 하는 요구사항 해결.',
            '동적 메타데이터 생성: Next.js의 generateMetadata를 활용하여 URL 기반으로 사용자별 메타데이터 동적 생성 스크립트',
            '동적 사이트맵 생성: API를 통해 DB에서 모든 사용자와 제품 리스트를 패치하여 자동으로 사이트맵 생성',
            '결과: 수백 개의 셀러 페이지와 제품 페이지가 검색 엔진에 자동 인덱싱되어 개별 노출',
        ],
        assets: [
            '/assets/projects/cambolink/1.png',
            '/assets/projects/cambolink/2.png',
            '/assets/projects/cambolink/3.png',
            '/assets/projects/cambolink/4.png',
            '/assets/projects/cambolink/5.png',
            '/assets/projects/cambolink/6.png',
            '/assets/projects/cambolink/7.png',
            '/assets/projects/cambolink/8.png',
            '/assets/projects/cambolink/9.png',
        ],
        mainAsset: 0,
        url: 'https://www.cambolinks.com',
        pin: false,
    },
    '기업 브랜딩 사이트': {
        title: '기업 브랜딩 사이트',
        description: '비주얼을 중심으로 브랜드 아이덴티티를 강조한 기업 브랜딩 사이트',
        features: [
            '풍부한 애니메이션을 활용한 브랜드 아이덴티티 연출',
            '이미지·영상 에셋 기반의 비주얼 중심 레이아웃 구성',
            '독특한 레이아웃과 인터랙션 디자인 구현'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'GSAP',
            'React Context API'
        ],
        duration: '2024-05 ~ 2024-08',
        contribution: [
            '개발인원 3명 중 1명으로 프론트엔드 개발 담당',
            '',
            '프론트엔드 아키텍처 설계 참여',
            '  - Next.js 14 App Router 기반 프로젝트 구조 설계',
            '  - 컴포넌트 계층 구조 설계 (공용 컴포넌트/페이지별 컴포넌트 분리 구조)',
            '  - Context API 기반 전역 상태 관리 구조 설계',
            '프론트엔드 주요 섹션 및 공용 컴포넌트 개발',
            '  - 공용 컴포넌트 및 주요 섹션 페이지 5개 이상 개발',
            '  - 반응형 UI 구현: PC/모바일 대응'
        ],
        totalDeveloper: 3,
        contributedPercentage: 40,
        frontEnd: true,
        backend: false,
        detail: [
            '### 복잡한 UI와 많은 양의 에셋으로 인한 성능 이슈를 해결하기 위해 최적화 처리',
            't: 고용량 이미지 에셋이 대량으로 포함된 페이지 구현',
            's: 이미지 최적화, 지연 로딩, 반응형 최적화 구현',
            ' 이미지 최적화: lazy load, placeholder blur 처리, AWS S3 가속화 설정으로 이미지 전송 속도 향상',
            ' 지연 로딩: Intersection Observer API 기반 커스텀 래퍼 컴포넌트 구현하여 뷰포트 진입 시에만 렌더링하도록 함으로써 초기 렌더링 비용 감소',
            ' 반응형 최적화: PC/모바일 환경별 최적화된 이미지 및 레이아웃 제공',
            '### 복잡한 UI 에니메이션 구현',
            't: 복잡한 스크롤 트리거 에니메이션 + 반응형 조합 요구사항',
            's: GSAP + AOS + JS/CSS 에니메이션 조합 구현',
            ' 애니메이션 라이브러리 선택적 활용: 복잡한 스크롤 기반 애니메이션은 GSAP(ScrollTrigger)로 구현, 간단한 fade-in/scroll 애니메이션은 AOS로 빠르게 구현하여 개발 효율성 확보',
            ' 라이브러리로 구현이 어려운 경우에는 CSS 애니메이션과 순수 JavaScript로 구현',
            '### 공용 컴포넌트 설계',
            ' Header, GNB, Footer, IntersectionAppearWrapper, 페이지 전환 로딩 처리',
            ' 확장성 고려: HTMLAttributes extends props',
            ' 가독성 향상: 상세 주석 처리하여 DX 향상'
        ],
        assets: [
            `/assets/projects/기업 브랜딩 사이트/1.gif`,
            `/assets/projects/기업 브랜딩 사이트/1.png`,
        ],
        mainAsset: null,
        url: 'https://portfoilo-sample-ce3e.vercel.app/branding-page',
        pin: false,
    },
    supplmarket: {
        title: 'Supplmarket',
        description: '운영팀, 셀러, 구매자 3자 구조의 공동구매 플랫폼',
        features: [
            '## 셀러 플랫폼',
            '공동구매 관리, 통계, 정산',
            '## 구매자 플랫폼',
            '상품 구매, 주문 관리, 환불/교환',
            '## 운영팀(어드민)',
            '공구 및 주문 관리',
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'Ant Design (Antd)',
            'Zustand',
            'Elysia',
            'Bun',
            'Prisma',
            'AWS EC2',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-08 ~ 2025-07',
        contribution: [
            '개발인원 2명 중 1명으로 풀스택 개발 담당',
            '',
            '프론트엔드/백엔드 아키텍쳐 설계 참여',
            '  - Next.js/Elysia(Node.js) Framework 기반 풀스택 구조',
            '고객 및 셀러용 서비스 풀스택 개발 전담',
            '- 고객용 서비스',
            '  - 상품 조회 · 장바구니',
            '  - 주문 및 결제 프로세스',
            '  - 주문 내역 관리 · 배송 추적',
            '  - 리뷰 시스템 · 교환/반품 시스템',
            '- 셀러용 서비스',
            '  - 홈 통계 대시보드',
            '  - 상품, 주문 관리 · 정산 관리',
            '  - 공동구매 상품, 스케줄, 상태 관리',
            '- 공통 기능',
            '  - 토스페이먼츠 결제 연동 및 웹훅 처리',
            '라이브 서비스 운영'
        ],
        totalDeveloper: 2,
        contributedPercentage: 50,
        frontEnd: true,
        backend: true,
        detail: [
            '### 역할·권한 기반 접근 제어',
            'Next.js App Router의 디렉토리 구조와 미들웨어를 활용해 역할별 라우팅 분리, Elysia 백엔드에서 JWT 기반 권한 검증으로 이중 보안 구현',
            '### UX 최적화',
            '유저 인터렉션, 에니메이션 효과, Infinite Scroll, 반응형 구현 등 UX 최적화',
            '피그마 디자인 시안에서 제공된 단순 UI 이상의 UX를 구현하고자 함.',
            '실제로 시연 시에 UI/UX의 완성도가 높다는 평가 받음',
            '### 짧은 비즈니스 로직의 변경 주기',
            't: 클라이언트가 기능변경 및 추가개발을 요청하는 주기가 잦고, 변경된 로직이 깊은 레벨의 설계까지 변경해야하는 경우가 많았음.',
            's: 개발자·PM 간의 일정 공유 및 우선순위 조율, 기술적 내용 전달 등을 통해 유연하게 대응.',
            '긴박한 일정 속에서 개발자 팀원, PM과의 커뮤니케이션 능력이 매우 중요하게 작용했고, 유연한 업무 대응 방식을 익힐 수 있었음.',
            '### 라이브 서비스 운영 경험',
            't: 라이브 환경에서 예외 케이스가 예상보다 훨씬 다양하다는 경험. 일례로 명확하게 정리되지 않은 결제 로직에서 다양한 케이스의 결제가 이뤄지며 이슈가 발생하였음.',
            's: 이에 결제 로직을 모듈화하여 통합 관리할 수 있도록 개선하고, 운영 데이터와 CS 사례를 분석하여 이를 처리할 수 있도록 웹훅 처리, 재실행 등의 방식으로 로직을 보완하였음.',
            '한 차례 개선 이후 결제 관련 문제 재발하지 않았음.'
        ],
        assets: [
            `/assets/projects/supplmarket/1.png`,
            `/assets/projects/supplmarket/2.png`,
            `/assets/projects/supplmarket/3.png`,
            `/assets/projects/supplmarket/4.png`,
            `/assets/projects/supplmarket/5.png`,
            `/assets/projects/supplmarket/6.png`,
            `/assets/projects/supplmarket/7.png`,
        ],
        mainAsset: 0,
        url: 'https://supplmarket.com',
        pin: true,
    },
    '포포넛 비즈니스': {
        title: '포포넛 비즈니스',
        description: '반려동물 호텔·유치원·미용실을 위한 매장 운영 플랫폼',
        features: [
            '매장 등록 및 예약·이용권·프로모션 관리',
            '고객·반려동물 정보 및 안심번호 기반 AI 통화 기록 관리',
            '통화 기록 기반 예약 자동 생성',
            '전자동의서·알림장 등 고객 커뮤니케이션 기능',
            '매출·정산 조회',
            '재고·판매물품 관리',
            '직원 관리 및 권한 설정',
            '플랜별 구독 및 기능 차등 제공'
        ],
        skills: [
            'Next.js',
            'React',
            'React Native',
            'Typescript',
            'Tailwind CSS',
            'Mui',
            'React Context API',
            'React Query',
            'Next Auth',
            'Openapi',
            'Sentry',
            'Expo',
            'Elysia',
            'Bun',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-11 - 2025-11',
        contribution: [
            '개발자 3명 중 1명으로 참여 (기능 단위 분담)',
            '',
            '서비스명 제안',
            '',
            '프론트엔드/백엔드 아키텍처 설계 참여',
            '  - Next.js App Router 기반 프론트엔드 아키텍처 설계',
            '  - React Native WebView 기반 웹앱 및 웹뷰-네이티브 앱 간 통신 아키텍처 설계',
            '프론트엔드/백엔드 6개 주요 기능 개발',
            '- 예약 관리',
            '- 고객 · 반려동물 관리',
            '- 직원 관리',
            '- 매출 통계',
            '- 구독 시스템',
            '- 웹앱 구현 및 출시',
            '- 라이브 서비스 운영',
            '  - 프로덕션 환경 모니터링 (Sentry + Clickup)',
            '  - 담당 기능 이슈 대응 및 추가 개발'
        ],
        totalDeveloper: 3,
        contributedPercentage: 33,
        frontEnd: true,
        backend: true,
        detail: [
            '### 커스텀 훅 네스팅을 활용한 로직 모듈화',
            '복잡한 예약관리 로직을 13개의 세부 Custom Hook으로 분리',
            'useReservationActions 메인 Hook에서 조합하여 기능 구성',
            '### RBAC 권한 제어 시스템',
            '업체별 커스텀 권한 설정 기능 구현',
            'PermissionWrapper 컴포넌트로 권한 체크 및 차단 UI 구현',
            '백엔드 권한 검증 + 프론트엔드 권한 차단 UI로 2중 차단 구현',
            '### WebView 구현',
            'JavaScript Code Injection과 postMessage 이벤트를 통한 웹 ↔ 앱 간 양방향 통신 구현',
            '1초 간격 쿠키 변경 감지를 통한 세션 유지, SecureStore 기반 토큰 저장, 라우팅 이벤트 감지로 쿠키 동기화',
            '### 반응형 구현',
            'SSR 방식에서 userAgent를 통해 기기 정보 파악하는 isMobileDevice 헬퍼 함수 구현하여, 기기에 맞는 페이지 렌더링',
            '### SEO 최적화',
            'sitemap.xml 동적 생성, semantic tag, metadata를 통해 매장별 링크 노출 최적화',
            '### 개발 환경 분리',
            'production / preview / development 환경으로 구분하여, 안정적인 개발 환경 구축',
            '### Sentry 통합 모니터링',
            '에러 발생시 알림/로그/화면 기록까지 직접 확인하여 대응',
            '프로덕션 환경 모니터링 및 버그 추적',
            '### SSR + IntersectionObserver로 SEO와 로딩 성능을 모두 최적화',
            '요구사항: SEO를 최적화하되, 로딩 성능 역시 최적화.',
            't: SEO를 최적화하기 위해서는 초기 로딩 시점에 검색엔진 봇에 노출되어야 하나, 이를 위해 모든 콘텐츠를 로드할 경우 로딩 성능이 현저히 떨어지는 문제.',
            's: 2단계 로딩 방식 적용',
            '    1. 텍스트 위주의 콘텐츠 → SSR 방식으로 렌더링',
            '    2. 이미지 위주의 콘텐츠 → InView로 분기 처리하여 CSR 지연 렌더링',
            // 'code',
            // 'code'
        ],
        assets: [
            `/assets/projects/포포넛 비즈니스/1.png`,
            `/assets/projects/포포넛 비즈니스/2.png`,
            `/assets/projects/포포넛 비즈니스/3.png`,
            `/assets/projects/포포넛 비즈니스/4.png`,
            `/assets/projects/포포넛 비즈니스/5.png`,
            `/assets/projects/포포넛 비즈니스/6.png`,
            `/assets/projects/포포넛 비즈니스/7.png`,
            `/assets/projects/포포넛 비즈니스/8.png`,
            `/assets/projects/포포넛 비즈니스/9.png`,
            `/assets/projects/포포넛 비즈니스/10.png`,
        ],
        mainAsset: 1,
        url: 'https://biz.pawpawnut.com',
        pin: true,
    },
    '포포넛 고객용': {
        title: '포포넛 고객용',
        description: '매장 운영 플랫폼 포포넛 비즈와 연동되는 고객용 반려동물 예약 서비스',
        features: [
            '반려동물 등록 및 예약 생성',
            '예약금 결제 및 예약 내역 관리',
            '이용권 사용(횟수권 / 금액권 / 픽업·드랍권)',
            '알림장 조회 및 업주와의 커뮤니케이션 기능 제공'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Tailwind CSS',
            'ShadCn',
            'Radix UI',
            'Mui',
            'Openapi',
            'Elysia',
            'Bun',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-11 - 2025-10',
        contribution: [
            '개발인원 2명 중 1명으로 풀스택 개발 참여',
            '',
            '프론트엔드/백엔드 아키텍처 설계 참여',
            '',
            '프론트엔드/백엔드 5개 주요 기능 UI 및 API 개발 (팀 내 기여도 80%)',
            '- 반려동물 관리',
            '  - 반려동물 정보 생성 및 관리 기능 제공',
            '- 예약 관리',
            '  - 장바구니, 예약 로직 및 관리 기능 제공',
            '- 이용권 시스템',
            '  - 이용권 사용 및 관리 로직',
            '- 알림장 사진 갤러리',
            '  - 조회 및 다운로드, 코멘트 기능 제공',
            '- 랜딩 페이지',
            '  - 사이트맵, 메타데이터, SEO 최적화'
        ],
        totalDeveloper: 2,
        contributedPercentage: 80,
        frontEnd: true,
        backend: true,
        detail: [
            '### 예약 시스템 비즈니스 로직 구현',
            '호텔/유치원/미용실 카테고리별 예약, 티켓(정률/정액), 프로모션, 반복 예약, 옵션 추가 등 가격 계산 로직을 백엔드에서 처리.',
            'Transaction을 통한 데이터 일관성 보장',
            '### OpenAPI 기반 타입 안정성 확보',
            'Swagger + openapi-fetch script로 타입 자동 생성',
            '### 디자인 시스템화',
            '디자인 토큰화: 디자인 시안의 변수값 -> JSON 자동 변환 스크립트 작성, 디자인 토큰을 사용한 일관된 UI 구현',
            '### 사용자 경험 강화',
            '스켈레톤, 세션 보존, 에니메이션 UI, 유저 인터렉션 등으로 사용자 경험 강화',
            '이미지 플레이스 홀더, nextImage 활용하여 이미지 최적화 및 로딩 성능 개선',
            '### 메모이제이션 통한 성능 최적화',
            '모바일 환경에서 동작하는 상황이 많은만큼, useMemo, useCallback으로 Memoization하여 불필요한 리렌더링 방지'
        ],
        assets: [
            `/assets/projects/포포넛 고객용/1.png`,
            `/assets/projects/포포넛 고객용/2.png`,
            `/assets/projects/포포넛 고객용/3.png`,
            `/assets/projects/포포넛 고객용/4.png`,
            `/assets/projects/포포넛 고객용/5.png`,
            `/assets/projects/포포넛 고객용/6.png`,
        ],
        mainAsset: 0,
        url: 'https://www.pawpawnut.com/',
        pin: false,
    },
    '포포넛 앱': {
        title: '포포넛 앱',
        description: '기존 고객용 플랫폼의 모바일 애플리케이션 버전',
        features: [
            '반려동물 등록 및 예약 생성, 예약금 결제, 예약 관리',
            '이용권 사용(횟수권 / 금액권 / 픽업·드랍권)',
            '알림장 조회 및 업주와 커뮤니케이션',
            '지도 기반 매장 탐색 기능',
            '앱 기반 UI/UX 개선',
            '펫케어 관련 카드뉴스·포스트 콘텐츠 제공',
            'AI 챗봇을 통한 업체·예약 관련 데이터 접근 지원'
        ],
        skills: [
            'React Native',
            'Expo',
            'EAS',
            'Typescript',
            'React Context API',
            'Elysia',
            'Bun',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2025-10 - 2025-11',
        contribution: [
            '개발인원 4명 중 1명으로 풀스택 개발 참여',
            '',
            '프론트엔드/백엔드 4개 주요 기능 UI 및 API 개발 (팀 내 기여도 25%)',
            '- 지도기반 매장찾기',
            '  - 지도 영역 변경시 min/max 좌표 기반 매장 검색',
            '  - 다중 필터 조건 처리',
            '  - 매장 Feature 추출 및 반환',
            '- 예약 내역 관리',
            '  - 예약 목록 및 상세 조회 기능 UI · API',
            '  - 반려동물/상태/날짜별 필터링',
            '- 반려동물 관리',
            '  - 반려동물 등록/수정',
            '  - AWS S3 Presigned URL 이미지 업로드 처리',
            '  - 반려동물 목록 조회 및 관리',
            '- 펫케어 콘텐츠',
            '  - 포스트/카드뉴스 콘텐츠 목록 및 상세 조회',
            '  - 다중 필터 조건 처리',
            '  - 콘텐츠 좋아요 기능'
        ],
        totalDeveloper: 4,
        contributedPercentage: 25,
        frontEnd: true,
        backend: true,
        detail: [
            '### 매장 탐색 API 연동',
            '지도에서 onRegionChangeComplete 이벤트 발생 시, 이동 완료한 영역의 min/max 좌표 값을 상태 값에 반영. 해당 영역 내에 포함되는 좌표값의 업체 필터링.',
            '선택된 영역 내 업체가 한정적이라는 점을 고려, 필터 선택 변경시 추가 API 호출 대신 클라이언트에서 기존 결과값을 필터링하도록 구현. 이로써 데이터 패치 딜레이가 발생하지 않는 빠른 결과 보장.',
            '클라이언트에서 필터링 가능하도록 백엔드에서 매장 Feature 추출하여 반환',
            'GroupBy와 JSON_ARRAYAGG를 사용하여 JSON 배열로 집계하여 반환',
            '### 상태 관리 패턴',
            '복잡한 상태 관리를 효율적이고 안정적으로 관리할 수 있는 방식',
            '기능 별 상태를 객체로 묶어 form 형태로 관리',
            // 'code',
            '상태 변경은 handleUpdateForm 함수로 통합 관리',
            // 'code',
            '여러 개의 필터를 변경 로직을 통합하여 관리',
            // 'code',
            '### 디테일한 스켈레톤 효과를 통한 UX 강화',
            '텍스트 스켈레톤 UI → 이미지 스켈레톤 UI를 순차적으로 표시함으로써 보다 자연스러운 로딩 효과.',
            '인피니트 스크롤 시, 초기로딩과 추가로딩을 구분하여 UI를 구현함으로써 사용자 경험 강화.'
        ],
        assets: [
            `/assets/projects/포포넛 앱/1.png`,
            `/assets/projects/포포넛 앱/2.png`,
            `/assets/projects/포포넛 앱/3.png`,
            `/assets/projects/포포넛 앱/4.png`,
            `/assets/projects/포포넛 앱/5.png`,
            `/assets/projects/포포넛 앱/6.png`,
            `/assets/projects/포포넛 앱/7.png`,
            `/assets/projects/포포넛 앱/8.png`,
            `/assets/projects/포포넛 앱/9.png`,
            `/assets/projects/포포넛 앱/10.png`,
            `/assets/projects/포포넛 앱/11.png`,
            `/assets/projects/포포넛 앱/12.png`,
            `/assets/projects/포포넛 앱/13.png`,
        ],
        mainAsset: 0,
        pin: false,
    },
    '포포넛 통합 서버': {
        title: '포포넛 통합 서버',
        description: '반려동물 매장 운영 플랫폼, 고객용 웹·앱 서비스를 통합 관리하는 서버 플랫폼',
        features: [
            '## 모든 포포넛 서비스의 데이터 처리, 연동, API 제공을 담당하는 통합 백엔드 시스템',
            '매장·예약·이용권·고객·직원 등 데이터 통합 관리',
            '웹·앱 고객용 서비스와 매장 운영 플랫폼 연동',
            '결제, 알림, 챗봇 등 서비스 전반 기능 지원',
            'API 제공 및 데이터 동기화 관리',
        ],
        skills: [
            'Elysia',
            'Bun',
            'Typescript',
            'Supabase',
            'Supabase Auth',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-11 - 2025-11',
        contribution: [
            '개발인원 3명 중 1명으로 풀스택 개발 담당',
            '',
            'DB · API 아키텍쳐 구조 설계 및 구현 참여',
            '',
            '백엔드 API 구현 참여',
            '- 포포넛 비즈 7개 주요 기능',
            '  - 회원가입 및 로그인 (일반 로그인 및 소셜 로그인 - 카카오/네이버/구글/애플)',
            '  - 고객 관리 (고객 프로필 생성/관리, 태깅, 고객-반려동물 통합/해제, 통계)',
            '  - 펫 관리 (펫 정보 생성/관리)',
            '  - 예약 관리 (예약 생성/관리, 상태 관리)',
            '  - 권한 관리 (직원/메뉴별 CRUD 권한, 팀리더/오너 권한 체계)',
            '  - 알림장 및 코멘트 (앨범/알림장 작성 및 댓글)',
            '  - 매출 관리 (예약/예약금/이용권 매출 통계 및 내역)',
            '- 포포넛 고객용 4개 주요 기능',
            '  - 펫 관리 (펫 정보 생성/관리)',
            '  - 예약 관리 (예약 생성/관리)',
            '  - 이용권 관리 (반려동물별 금액권/횟수권/횟수권/왕복권)',
            '  - 업체 정보 조회',
            '',
            '에러 모니터링 시스템 구축 전담 (Sentry, Clickup 연동)',
            '',
            '4개 레거시 시스템 데이터 마이그레이션 전담'
        ],
        totalDeveloper: 3,
        contributedPercentage: 33,
        frontEnd: true,
        backend: true,
        detail: [
            '### API 아키텍쳐',
            'Elysia 프레임워크의 그룹 라우팅 활용',
            'URL 경로와 디렉토리 구조 일치하도록 구현 (/api/v1/auth/b/reservation/list → auth/b/reservation/list/)',
            '역할 기반 라우트 분리 (admin/a, business/b, customer/c, guest)',
            '미들웨어를 통한 역할별 접근 제어 (derive를 활용한 권한 검증 및 데이터 하달)',
            '### 데이터베이스 설계',
            '고객 원본 데이터를 통해 업체별 인스턴스 데이터를 생성하여, 고객정보 통합 시스템 구축',
            '(T_business: 원본 데이터 → T_business_customer: 인스턴스 데이터)',
            '### 성능 최적화',
            '대기시간 단축하기 위해 Promise.all 로 독립 쿼리 병렬 처리',
            'Transaction 활용으로 데이터 일관성 유지 및 롤백 처리',
            '### 에러 모니터링',
            'Sentry webhook 수신 → ClickUp API로 자동 task 생성',
            '에러 우선순위 자동 할당, 상세 정보(URL, 에러 ID, 에러 메세지 등) 포함',
            '에러 대응 체계 구축 및 대응 속도 개선',
            '### RBAC 권한 관리 시스템',
            '계층 구조: Owner(전체 권한) → Team Leader(부가 권한) → 일반 직원(메뉴별 세부 권한)',
            '메뉴 단위 권한 제어 (CRUD 분리)',
            'API router에서 권한 실시간 검증 (assertPermission)',
            '업체별 커스텀 권한 설정 기능 제공',
            '### 데이터 마이그레이션',
            '4개 이상 레거시 시스템(아하소프트, 그루머노트, 티피, 이노펫) 데이터 변환',
            '데이터 매핑 자동화(고객/반려동물/예약 정보 변환)',
            '순차 처리와 API 호출 간 딜레이를 통한 서버 부하 최소화',
            '### drizzle db pull',
            '개발 환경에서 서버 시작 시 자동 스키마 동기화 (bun drizzle-kit pull)',
            '개발자 경험 향상 및 스키마 변경 감지'
        ],
        assets: [
        ],
        mainAsset: 0,
        pin: true,
    }
}

export default projects;