const projects = {
    cambolink: {
        title: 'Cambolink',
        description: '셀러별 공동구매 페이지를 제공하는 셀러 전용 공동구매 플랫폼',
        features: [
            '셀러별 개인 공동구매 페이지 제공',
            '상품 등록 및 홍보 링크 생성 기능',
            '구매자의 공동구매 신청 기능',
            '구매자 신청 리스트 다운로드 기능',
            '셀러 전용 유료 플랜 결제 및 상품 슬롯 확장 기능'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'Recoil',
            'Fastify',
            'Node.js',
            'Knex.js',
            'AWS Lambda',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-03 - 2024-06',
        contribution: [
            '개발인원 3명 중 1명으로 풀스택 개발 참여',
            '',
            '프론트엔드/백엔드 아키텍처 설계 참여',
            '  - 멀티 테넌트 아키텍처: Next.js 동적 라우팅 기반 사용자별 페이지 시스템 설계',
            '  - 서버리스 백엔드: AWS Lambda + Fastify 기반 확장 가능한 API 아키텍처 구축',
            '프론트엔드/백엔드 5개 주요 기능 · 로직 개발 (35%)',
            '  - 셀러 페이지 관리 기능 (페이지 할당, 동적 라우팅, SEO 최적화, 커스터마이징)',
            '  - 제품 관리 기능 (4단계 업로드 프로세스, 임시 저장, 드래그 앤 드롭 재정렬)',
            '  - 공동구매 신청 기능',
            '  - 프로필 및 페이지 커스터마이즈 기능 (이미지 업로드, 배경 설정)',
            '  - 티켓 기반 비즈니스 로직 (보유 티켓에 따른 권한 제한 로직)',
            '  - 공용 컴포넌트 개발 (Recoil 기반 상태관리, 모달 · 토스트 시스템)',
            '라이브 서비스 운영 전담',
        ],
        totalDeveloper: 3,
        contributedPercentage: 40,
        frontEnd: true,
        backend: true,
        detail: [
            '### 서버리스 아키텍처 설계 및 구현',
            'Next.js / Fastify로 구성된 풀스택 프로젝트를 AWS Lambda 서버리스 환경으로 구성. ',
            '서버 관리 부담 없이 운영할 수 있도록 함.',
            '### 동적 SEO 최적화 시스템 구축',
            '각 셀러의 pageLink별로 검색 엔진에 개별 노출되어야 하는 요구사항 해결.',
            '동적 메타데이터 생성: Next.js의 generateMetadata를 활용하여 URL 기반으로 사용자별 메타데이터 동적 생성 스크립트',
            'code',
            '동적 사이트맵 생성: API를 통해 DB에서 모든 사용자와 제품 리스트를 패치하여 자동으로 사이트맵 생성',
            'code',
            '결과: 수백 개의 셀러 페이지와 제품 페이지가 검색 엔진에 자동 인덱싱되어 개별 노출',
            '### 크메르어 다국어 지원 및 UI 이슈 해결',
            '크메르어를 JSON 타입 데이터로 매핑하여 번역 작업과 개발 작업을 분리하여 효율성 확보.',
            '결과: 크메르어 다국어 지원 및 UI 이슈 해결',
            'code',
            '문제: 크메르어는 한글/영어 대비 문자 폭이 넓어 동일한 텍스트 길이에서 UI 깨짐 발생',
            '해결:',
            '- CSS에서 min-width/max-width 지정하여 유연한 레이아웃 대응',
            '- text-overflow: ellipsis로 긴 텍스트 처리',
            '- 반응형 미디어 쿼리로 다양한 화면 크기 대응',
            '- 불가피한 경우 디자인 수정 요청하여 UX 개선',
            'code',
            '결과: 크메르어 환경에서도 안정적인 UI 제공 및 사용자 경험 개선'
        ],
        assets: [
            '/assets/projects/cambolink/1.png',
            '/assets/projects/cambolink/2.png',
            '/assets/projects/cambolink/3.png',
            '/assets/projects/cambolink/4.png',
            '/assets/projects/cambolink/5.png',
            '/assets/projects/cambolink/6.png',
            '/assets/projects/cambolink/7.png',
            '/assets/projects/cambolink/8.png',
            '/assets/projects/cambolink/9.png',
        ],
        mainAsset: 0
    },
    '기업 브랜딩 사이트': {
        title: '기업 브랜딩 사이트',
        description: '비주얼을 중심으로 브랜드 아이덴티티를 강조한 기업 브랜딩 사이트',
        features: [
            '풍부한 애니메이션을 활용한 브랜드 아이덴티티 연출',
            '이미지·영상 에셋 기반의 비주얼 중심 레이아웃 구성',
            '독특한 레이아웃과 인터랙션 디자인 구현'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'GSAP',
            'React Context API'
        ],
        duration: '2024-05 ~ 2024-08',
        contribution: [
            '개발인원 3명 중 1명으로 프론트엔드 개발 담당',
            '',
            '프론트엔드 아키텍처 설계 참여',
            '  - Next.js 14 App Router 기반 프로젝트 구조 설계',
            '  - 컴포넌트 계층 구조 설계 (공용 컴포넌트/페이지별 컴포넌트 분리 구조)',
            '  - Context API 기반 전역 상태 관리 구조 설계',
            '프론트엔드 주요 섹션 및 공용 컴포넌트 개발',
            '  - 공용 컴포넌트 및 주요 섹션 페이지 5개 이상 개발',
            '  - 반응형 UI 구현: PC/모바일 대응'
        ],
        totalDeveloper: 3,
        contributedPercentage: 40,
        frontEnd: true,
        backend: false,
        detail: [
            '### 복잡한 UI와 많은 양의 에셋으로 인한 성능 이슈를 해결하기 위해 최적화 처리',
            '- 이미지 최적화: Next Image 활용하여 lazy load, 크기 지정, placeholder 적용',
            '- AWS S3 가속화 설정으로 이미지 전송 속도 향상',
            '- 지연 로딩: Intersection Observer API 기반 커스텀 컴포넌트(IntersectionAppearDiv) 구현하여 뷰포트 진입 시에만 렌더링하도록 함으로써 초기 렌더링 비용 감소',
            '- 반응형 최적화: PC/모바일 환경별 최적화된 이미지 및 레이아웃 제공',
            '### 복잡한 UI 에니메이션 구현',
            '- 요구사항에 맞춰 다양한 애니메이션 기법을 선택 적용.',
            '- 애니메이션 라이브러리 선택적 활용: 복잡한 스크롤 기반 애니메이션은 GSAP(ScrollTrigger)로 구현, 간단한 fade-in/scroll 애니메이션은 AOS로 빠르게 구현하여 개발 효율성 확보',
            '- 라이브러리로 구현이 어려운 경우에는 CSS 애니메이션과 순수 JavaScript로 구현',
            '- 페이지 전환 애니메이션: useDelayRouter 커스텀 훅 구현으로 Next.js Router의 사용 방법을 유지하여 개발자 경험을 향상하고, 페이지 전환 시 로딩 애니메이션을 통일',
            '### 공용 컴포넌트 설계',
            '- Header, GNB, Footer, IntersectionAppearDiv, 페이지 전환 로딩 처리',
            '- 확장성 고려: React의 HTMLAttributes를 extends하여 기본 HTML 속성들을 그대로 활용할 수 있도록 설계하여 활용도 극대화',
            '- 가독성 향상: 복잡한 로직이나 추가된 기능에 대해 주석 처리하여 다른 개발자들의 이해도 향상'
        ],
        assets: [
            `/assets/projects/기업 브랜딩 사이트/1.mov`,
            `/assets/projects/기업 브랜딩 사이트/1.png`,
        ],
        mainAsset: null
    },
    supplmarket: {
        title: 'Supplmarket',
        description: '운영팀, 셀러, 구매자 3자 구조의 공동구매 플랫폼',
        features: [
            '## 셀러 플랫폼',
            '공동구매 상품 탐색 및 신청',
            '공동구매 운영·참여자 관리',
            '판매/구매 내역 및 정산 관리',
            '통계 대시보드 제공',
            '## 구매자 플랫폼',
            '일반 상품 및 공동구매 상품 구매',
            '주문/배송 조회',
            '환불·교환 처리',
            '## 운영팀(어드민)',
            '셀러·구매자·상품·주문 관리',
            '정산 및 운영 지표 모니터링'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'Ant Design (Antd)',
            'Zustand',
            'Elysia',
            'Bun',
            'Prisma',
            'AWS EC2',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-08 ~ 2025-07',
        contribution: [
            '개발인원 2명 중 1명으로 풀스택 개발 담당',
            '',
            '프론트엔드/백엔드 아키텍쳐 설계 참여',
            '  - Next.js/Elysia 프레임워크로 Node.js 기반 풀스택 구조',
            '고객 및 셀러용 서비스 풀스택 개발 전담',
            '- 고객용 서비스',
            '  - 상품 조회 · 장바구니 기능',
            '  - 주문 및 결제 프로세스 (묶음 주문)',
            '  - 주문 내역 관리 · 배송 추적 기능',
            '  - 리뷰 시스템 · 교환/반품 시스템 (전체/일부)',
            '  - 마이페이지',
            '- 셀러용 서비스',
            '  - 홈 대시보드 (매출, 수익, 배송현황 등 통계)',
            '  - 상품, 주문 관리 · 정산 관리',
            '  - 공동구매 관리 (상품, 스케줄, 상태 관리)',
            '- 공통 기능',
            '  - 토스페이먼츠 결제 연동 및 웹훅 처리',
            '  - 알림 시스템 (알림톡/SMS/푸시)',
            '라이브 서비스 운영'
        ],
        totalDeveloper: 2,
        contributedPercentage: 50,
        frontEnd: true,
        backend: true,
        detail: [
            '### 역할·권한 기반 접근 제어',
            'admin/seller/user, authed/guest로 역할과 권한을 디렉토리 단위로 나누어 관리',
            'Next.js App Router의 디렉토리 구조와 미들웨어를 활용해 역할별 라우팅 분리, Elysia 백엔드에서 JWT 기반 권한 검증으로 이중 보안 구현',
            '설계 및 추가개발 단계에서 권한·역할 별로 명확히 구분하여 개발',
            '### 사용자 경험 강화한 프론트엔드 개발',
            '유저 인터렉션, 에니메이션 효과, 인피니트 스크롤, 반응형 등 사용자 경험 향상시킬 수 있는 요소들을 강화하여 프론트엔드 개발 진행하였음.',
            '실제로 시연 시에 UI/UX의 완성도가 높다는 평가 받을 수 있었음.',
            '### 짧은 비즈니스 로직의 변경 주기',
            '클라이언트가 기능변경 및 추가개발을 요청하는 주기가 잦고, 변경된 로직이 깊은 레벨의 설계까지 변경해야하는 경우가 많았음.',
            '이에 데드라인을 맞추기 위해 빠르게 비즈니스 니즈를 파악하여 대응한 후, 추후 개발자·PM들 간의 조율을 통해 로직을 일관성 있게 통합하고 모듈 기반으로 리팩토링 진행하여 유지보수성 높이는 방식으로 개발함.',
            '긴박한 일정 속에서 개발자 팀원, PM과의 커뮤니케이션 능력이 매우 중요하게 작용했고, 유연한 업무 대응 방식을 익힐 수 있었음.',
            '### 라이브 서비스 운영 경험',
            '직접 개발한 서비스를 라이브로 운영하는 과정에서 예외 케이스가 예상보다 훨씬 다양하다는 점을 확인함. 일례로 명확하게 정리되지 않은 결제 로직에서 다양한 케이스의 결제가 이뤄지며 이슈가 발생하였음.',
            '이에 결제 로직을 모듈화하여 통합 관리할 수 있도록 개선하고, 운영 데이터와 CS 사례를 분석하여 이를 처리할 수 있도록 웹훅 처리, 재실행 등의 방식으로 로직을 보완하였음. 한 차례 개선 이후 결제 관련 문제 재발하지 않았음.'
        ],
        assets: [
            `/assets/projects/supplmarket/1.png`,
            `/assets/projects/supplmarket/2.png`,
            `/assets/projects/supplmarket/3.png`,
            `/assets/projects/supplmarket/4.png`,
            `/assets/projects/supplmarket/5.png`,
            `/assets/projects/supplmarket/6.png`,
            `/assets/projects/supplmarket/7.png`,
        ],
        mainAsset: 0
    },
    '포포넛 비즈니스': {
        title: '포포넛 비즈니스',
        description: '반려동물 호텔·유치원·미용실을 위한 매장 운영 플랫폼',
        features: [
            '매장 등록 및 예약·이용권·프로모션 관리',
            '고객·반려동물 정보 및 안심번호 기반 AI 통화 기록 관리',
            '통화 기록 기반 예약 자동 생성',
            '전자동의서·알림장 등 고객 커뮤니케이션 기능',
            '매출·정산 조회',
            '재고·판매물품 관리',
            '직원 관리 및 권한 설정',
            '플랜별 구독 및 기능 차등 제공'
        ],
        skills: [
            'Next.js',
            'React',
            'React Native',
            'Typescript',
            'Tailwind CSS',
            'Mui',
            'React Context API',
            'React Query',
            'Next Auth',
            'Openapi',
            'Sentry',
            'Expo',
            'Elysia',
            'Bun',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-11 - 2025-11',
        contribution: [
            '개발자 3명 중 1명으로 참여 (기능 단위 분담)',
            '',
            '서비스명 제안',
            '',
            '프론트엔드/백엔드 아키텍처 설계 참여',
            '  - Next.js App Router 기반 프론트엔드 아키텍처 설계',
            '  - React Native WebView 기반 웹앱 및 웹뷰-네이티브 앱 간 통신 아키텍처 설계',
            '프론트엔드/백엔드 6개 주요 기능 개발',
            '- 예약 관리',
            '  - 예약 생성/관리 워크플로우',
            '  - 예약 일정 관리 및 스케쥴러 자동 상태 변경 로직 (Cron Job 기반 예약 시작/종료 시 자동 상태 업데이트)',
            '  - 이용권/직접 결제/예약금/프로모션 적용 가격 계산 로직',
            '  - 운영시간, 지정날짜 예약차단, 정원 적용 예약 차단 기능',
            '  - 통화내역 기반 자동 예약 생성 기능',
            '- 고객 · 반려동물 관리',
            '  - 고객 · 반려동물 정보 생성/관리 워크플로우',
            '  - 고객-반려동물 매핑',
            '  - 통화내역/프로모션/알림 관리 체계',
            '  - 이미지/영상 알림장 기능 (다중 파일 업로드, 썸네일 생성, 영상 썸네일 추출)',
            '- 직원 관리',
            '  - 팀별 권한 생성 기능',
            '  - 차등 권한 부여 로직 (메뉴별 read/create/update/delete 권한 세분화)',
            '  - 직원별 메뉴 접근 권한 제어 (PermissionWrapper 컴포넌트, 백엔드 권한 검증 미들웨어)',
            '- 매출 통계',
            '  - 매출 통계 대시보드 구축',
            '  - 예약/예약금/이용권별 매출 내역 조회',
            '- 구독 시스템',
            '  - 구독 플랜(루키/스타터/스탠다드/프리미엄)에 따른 차등적 기능 제공 시스템',
            '  - 플랜별 기능 제한 로직 및 UI 가드 컴포넌트 구현 (RestrictedFeatureGuard)',
            '- 웹앱 구현 및 출시',
            '  - 앱 내에서 React Native WebView를 활용한 웹앱 구현',
            '  - 앱스토어·플레이스토어 출시',
            '  - 웹 ↔ 앱 간 통신을 통해 로그인 세션 처리 (postMessage 기반 양방향 통신)',
            '  - 쿠키 동기화 및 세션 관리 (1초 간격 쿠키 변경 감지, SecureStore 기반 토큰 저장, Next.js 라우팅 이벤트 감지)',
            '- 라이브 서비스 운영',
            '  - 프로덕션 환경 모니터링 (Sentry + Clickup)',
            '  - 담당 기능 이슈 대응 및 추가 개발'
        ],
        totalDeveloper: 3,
        contributedPercentage: 33,
        frontEnd: true,
        backend: true,
        detail: [
            '### 커스텀 훅 네스팅을 활용한 로직 모듈화',
            '복잡한 예약관리 로직을 13개의 세부 커스텀 훅으로 분리 (useReservationData, useCustomerSelection, useServiceSelection, useTicketManagement, useScheduleAndAddress, usePayment, useValidation, usePromotion, usePriceCalculation, useReservationAPI 등)',
            '각 훅을 useReservationActions 메인 훅에서 조합하여 기능 구성',
            '→ 유지보수성 확보 및 추가 개발 난이도와 속도 단축',
            '→ 도메인별 책임 분리로 테스트 용이성 향상',
            '### NextAuth 다중 소셜로그인',
            '카카오/구글/네이버/애플 소셜로그인 구현',
            'NextAuth 이용하여 간결하고 빠르게 구현',
            'Credentials Provider와 소셜 로그인을 통합하여 단일 인증 플로우 구성',
            '### 통합 권한 제어',
            'PermissionWrapper로 권한에 따른 접근 제어 (메뉴별 read/create/update/delete 권한 세분화)',
            'RestrictedFeatureGuard 컴포넌트로 권한에 따른 기능 제어 및 플랜별 기능 제한 UI 구현',
            '백엔드 권한 검증 미들웨어와 프론트엔드 권한 체크를 이중화하여 보안 강화',
            '### 웹앱 구현',
            '로그인-웹, 세션 유지-앱 구조를 위해 JavaScript Code Injection과 postMessage 이벤트를 통한 웹 ↔ 앱 간 양방향 통신 구현',
            '1초 간격 쿠키 변경 감지, SecureStore 기반 토큰 저장, 라우팅 이벤트 감지로 쿠키 동기화',
            '### 반응형',
            'PC/모바일 별로 다른 layout 적용',
            '서버 렌더링 시 userAgent를 통해 기기 정보 파악하는 isMobileDevice 헬퍼 함수 구현하여, 기기에 맞는 페이지 렌더링',
            '### SEO 최적화',
            '매장별 페이지가 검색 엔진에 효과적으로 노출될 수 있도록 DB로부터 동적으로 매장 리스트를 패치하여 사이트맵 생성.',
            '시맨틱 HTML5 태그(<main>, <section>, <nav>, 헤딩 계층)로 콘텐츠 구조 표현',
            '메타데이터, 본문 타겟 키워드를 자연스럽게 배치함으로써 검색 최적화 구현',
            '사이트앱에서 동적으로 메타데이터 생성하여, 반려동물 관련 키워드 검색시 구글, 네이버 검색 엔진에서 상위권 노출.',
            '### 환경별 분리 운영',
            'main/prod/dev 환경으로 구분하여, 라이브/테스트/개발 환경에서 사용',
            '### Sentry 통합 모니터링',
            '에러 발생시 알림/로그/화면 기록까지 직접 확인하여 대응',
            '프로덕션 환경 모니터링 및 버그 추적',
            '### SSR + IntersectionObserver로 SEO와 로딩 성능을 모두 최적화',
            '요구사항: SEO를 최적화하되, 로딩 성능 역시 최적화.',
            '문제: SEO를 최적화하기 위해서는 초기 로딩 시점에 검색엔진 봇에 노출되어야 하나, 이를 위해 모든 콘텐츠를 로드할 경우 로딩 성능이 현저히 떨어지는 문제.',
            '해결: 2단계 로딩 방식 적용',
            '    1. 크롤링되어야 하는 영역 → SSR 방식으로 렌더링',
            '    2. 무거운 영역 → InView로 분기 처리하여 지연 렌더링',
            'code',
            'code'
        ],
        assets: [
            `/assets/projects/포포넛 비즈니스/1.png`,
            `/assets/projects/포포넛 비즈니스/2.png`,
            `/assets/projects/포포넛 비즈니스/3.png`,
            `/assets/projects/포포넛 비즈니스/4.png`,
            `/assets/projects/포포넛 비즈니스/5.png`,
            `/assets/projects/포포넛 비즈니스/6.png`,
            `/assets/projects/포포넛 비즈니스/7.png`,
            `/assets/projects/포포넛 비즈니스/8.png`,
            `/assets/projects/포포넛 비즈니스/9.png`,
            `/assets/projects/포포넛 비즈니스/10.png`,
        ],
        mainAsset: 1
    },
    '포포넛 고객용': {
        title: '포포넛 고객용',
        description: '매장 운영 플랫폼 포포넛 비즈와 연동되는 고객용 반려동물 예약 서비스',
        features: [
            '반려동물 등록 및 예약 생성',
            '예약금 결제 및 예약 내역 관리',
            '이용권 사용(횟수권 / 금액권 / 픽업·드랍권)',
            '알림장 조회 및 업주와의 커뮤니케이션 기능 제공'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Tailwind CSS',
            'ShadCn',
            'Radix UI',
            'Mui',
            'Openapi',
            'Elysia',
            'Bun',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-11 - 2025-10',
        contribution: [
            '개발인원 2명 중 1명으로 풀스택 개발 참여',
            '',
            '프론트엔드/백엔드 아키텍처 설계 참여',
            '',
            '프론트엔드/백엔드 5개 주요 기능 UI 및 API 개발 (팀 내 기여도 80%)',
            '- 반려동물 관리',
            '  - 반려동물 생성/수정/관리 API 및 UI',
            '  - 반려동물 별 이용권 체계 구현',
            '  - 반려동물-고객 관계 관리',
            '- 예약 관리',
            '  - 예약 생성/수정/조회/취소 API 및 UI',
            '  - 다중 예약 일괄 처리',
            '  - 장바구니 기능',
            '  - 예약 상태 관리 (확인필요, 확정, 완료 등)',
            '- 이용권 시스템',
            '  - 이용권 (횟수권/금액권) 및 픽업/드랍 이용권 (횟수권)',
            '  - 이용권 타입 별 관리',
            '  - 이용권 사용 처리',
            '- 알림장 사진 갤러리',
            '  - 알림장 사진/비디오 조회',
            '  - 사진별 코멘트 작성/조회 기능',
            '  - 사진 다운로드 (단건/전체 ZIP)',
            '  - Swiper 기반 갤러리 UI',
            '- 랜딩 페이지',
            '  - 사이트맵, 메타데이터, SEO 최적화'
        ],
        totalDeveloper: 2,
        contributedPercentage: 80,
        frontEnd: true,
        backend: true,
        detail: [
            '### 예약 시스템 비즈니스 로직 구현',
            '호텔/유치원/미용실 카테고리별 예약, 티켓(횟수권/금액권/왕복권), 프로모션(정률/정액), 반복 예약, 옵션 추가 등 가격 계산 로직을 백엔드에서 처리. 트랜잭션을 통한 데이터 일관성 보장',
            '### OpenAPI 기반 타입 안정성 확보',
            '백엔드 Swagger 문서를 기반으로 openapi-typescript로 타입을 자동 생성하여, 프론트엔드에서 API 호출 시 컴파일 타임 타입 체크 및 자동완성 지원. openapi-fetch를 활용한 타입 안전한 API 클라이언트 구현으로 런타임 에러 감소',
            '### 디자인 시스템화',
            '디자인 시안에 따라 공용 컴포넌트를 구현하여 개발 속도를 높이고, 통일성 및 재사용성 확보',
            '디자인 토큰화: 디자인 시안의 변수값을 JSON으로 자동 변환하는 스크립트를 작성하여, 디자인 토큰을 사용한 일관된 UI 구현',
            '### 사용자 경험 강화',
            '스켈레톤, 세션 보존, 에니메이션 UI, 유저 인터렉션 등으로 사용자 경험 강화',
            '이미지 플레이스 홀더, nextImage 활용하여 이미지 최적화 및 로딩 성능 개선',
            '### 메모이제이션 통한 성능 최적화',
            '모바일 환경에서 동작하는 상황이 많은만큼, useMemo, useCallback으로 메모이제이션하여 불필요한 리렌더링 방지'
        ],
        assets: [
            `/assets/projects/포포넛 고객용/1.png`,
            `/assets/projects/포포넛 고객용/2.png`,
            `/assets/projects/포포넛 고객용/3.png`,
            `/assets/projects/포포넛 고객용/4.png`,
            `/assets/projects/포포넛 고객용/5.png`,
            `/assets/projects/포포넛 고객용/6.png`,
        ],
        mainAsset: 0
    },
    '포포넛 앱': {
        title: '포포넛 앱',
        description: '기존 고객용 플랫폼의 모바일 애플리케이션 버전',
        features: [
            '반려동물 등록 및 예약 생성, 예약금 결제, 예약 관리',
            '이용권 사용(횟수권 / 금액권 / 픽업·드랍권)',
            '알림장 조회 및 업주와 커뮤니케이션',
            '지도 기반 매장 탐색 기능',
            '앱 기반 UI/UX 개선',
            '펫케어 관련 카드뉴스·포스트 콘텐츠 제공',
            'AI 챗봇을 통한 업체·예약 관련 데이터 접근 지원'
        ],
        skills: [
            'React Native',
            'Expo',
            'EAS',
            'Typescript',
            'React Context API',
            'Elysia',
            'Bun',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2025-10 - 2025-11',
        contribution: [
            '개발인원 4명 중 1명으로 풀스택 개발 참여',
            '',
            '프론트엔드/백엔드 4개 주요 기능 UI 및 API 개발 (팀 내 기여도 25%)',
            '- 지도기반 매장찾기',
            '  - 지도 영역 변경시 min/max 좌표 기반 매장 검색',
            '  - 다중 필터 조건 처리',
            '  - 매장 Feature 추출 및 반환',
            '- 예약 내역 관리',
            '  - 예약 목록 및 상세 조회 기능 UI · API',
            '  - 반려동물/상태/날짜별 필터링',
            '- 반려동물 관리',
            '  - 반려동물 등록/수정',
            '  - AWS S3 Presigned URL 이미지 업로드 처리',
            '  - 반려동물 목록 조회 및 관리',
            '- 펫케어 콘텐츠',
            '  - 포스트/카드뉴스 콘텐츠 목록 및 상세 조회',
            '  - 다중 필터 조건 처리',
            '  - 콘텐츠 좋아요 기능'
        ],
        totalDeveloper: 4,
        contributedPercentage: 25,
        frontEnd: true,
        backend: true,
        detail: [
            '### 매장 탐색 API 연동',
            '지도에서 onRegionChangeComplete 이벤트 발생 시, 이동 완료한 영역의 min/max 좌표 값을 상태 값에 반영. 해당 영역 내에 포함되는 좌표값의 업체 필터링.',
            '선택된 영역 내 업체가 한정적이라는 점을 고려, 필터 선택 변경시 추가 API 호출 대신 클라이언트에서 기존 결과값을 필터링하도록 구현. 이로써 데이터 패치 딜레이가 발생하지 않는 빠른 결과 보장.',
            '클라이언트에서 필터링 가능하도록 백엔드에서 매장 Feature 추출하여 반환',
            'GroupBy와 JSON_ARRAYAGG를 사용하여 JSON 배열로 집계하여 반환',
            '### 상태 관리 패턴',
            '복잡한 상태 관리를 효율적이고 안정적으로 관리할 수 있는 방식',
            '기능 별 상태를 객체로 묶어 form 형태로 관리',
            'code',
            '상태 변경은 handleUpdateForm 함수로 통합 관리',
            'code',
            'useMemo, useCallback을 사용하여 불필요한 리렌더링 차단',
            '여러 개의 필터를 변경 로직을 통합하여 관리',
            'code',
            '### 디테일한 스켈레톤 효과를 통한 UX 강화',
            '텍스트 스켈레톤 UI → 이미지 스켈레톤 UI를 순차적으로 표시함으로써 보다 자연스러운 로딩 효과.',
            '인피니트 스크롤 시, 초기로딩과 추가로딩을 구분하여 UI를 구현함으로써 사용자 경험 강화.'
        ],
        assets: [
            `/assets/projects/포포넛 앱/1.png`,
            `/assets/projects/포포넛 앱/2.png`,
            `/assets/projects/포포넛 앱/3.png`,
            `/assets/projects/포포넛 앱/4.png`,
            `/assets/projects/포포넛 앱/5.png`,
            `/assets/projects/포포넛 앱/6.png`,
            `/assets/projects/포포넛 앱/7.png`,
            `/assets/projects/포포넛 앱/8.png`,
            `/assets/projects/포포넛 앱/9.png`,
            `/assets/projects/포포넛 앱/10.png`,
            `/assets/projects/포포넛 앱/11.png`,
            `/assets/projects/포포넛 앱/12.png`,
            `/assets/projects/포포넛 앱/13.png`,
        ],
        mainAsset: 0
    },
    '포포넛 통합 서버': {
        title: '포포넛 통합 서버',
        description: '반려동물 매장 운영 플랫폼, 고객용 웹·앱 서비스를 통합 관리하는 서버 플랫폼',
        features: [
            '모든 서비스의 데이터 처리, 연동, API 제공을 담당하는 백엔드 시스템',
            '매장·예약·이용권·고객·직원 등 데이터 통합 관리',
            '웹·앱 고객용 서비스와 매장 운영 플랫폼 연동',
            '결제, 알림, 챗봇 등 서비스 전반 기능 지원',
            'API 제공 및 데이터 동기화 관리',
            '통계 및 운영 관리 지원'
        ],
        skills: [
            'Elysia',
            'Bun',
            'Typescript',
            'Supabase',
            'Supabase Auth',
            'Drizzle',
            'Swagger',
            'AWS EB',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-11 - 2025-11',
        contribution: [
            '개발인원 3명 중 1명으로 풀스택 개발 담당',
            '',
            'DB · API 아키텍쳐 구조 설계 및 구현 참여',
            '',
            '백엔드 API 구현 참여',
            '- 포포넛 비즈 7개 주요 기능',
            '  - 회원가입 및 로그인 (일반 로그인 및 소셜 로그인 - 카카오/네이버/구글/애플)',
            '  - 고객 관리 (고객 프로필 생성/관리, 태깅, 고객-반려동물 통합/해제, 통계)',
            '  - 펫 관리 (펫 정보 생성/관리)',
            '  - 예약 관리 (예약 생성/관리, 상태 관리)',
            '  - 권한 관리 (직원/메뉴별 CRUD 권한, 팀리더/오너 권한 체계)',
            '  - 알림장 및 코멘트 (앨범/알림장 작성 및 댓글)',
            '  - 매출 관리 (예약/예약금/이용권 매출 통계 및 내역)',
            '- 포포넛 고객용 4개 주요 기능',
            '  - 펫 관리 (펫 정보 생성/관리)',
            '  - 예약 관리 (예약 생성/관리)',
            '  - 이용권 관리 (반려동물별 금액권/횟수권/횟수권/왕복권)',
            '  - 업체 정보 조회',
            '',
            '에러 모니터링 시스템 구축 전담 (Sentry, Clickup 연동)',
            '',
            '4개 레거시 시스템 데이터 마이그레이션 전담'
        ],
        totalDeveloper: 3,
        contributedPercentage: 33,
        frontEnd: true,
        backend: true,
        detail: [
            '### API 아키텍쳐',
            'Elysia 프레임워크의 그룹 라우팅 활용',
            'URL 경로와 디렉토리 구조 일치하도록 구현 (/api/v1/auth/b/reservation/list → auth/b/reservation/list/)',
            '역할 기반 라우트 분리 (admin/a, business/b, customer/c, guest)',
            '미들웨어를 통한 역할별 접근 제어 (derive를 활용한 권한 검증 및 데이터 하달)',
            '### 데이터베이스 설계',
            '원본 데이터로 업체별 인스턴스 데이터를 생성하여, 고객정보 통합 시스템 구축 (T_business: 원본 데이터 → T_business_customer: 인스턴스 데이터)',
            '데이터 격리 및 업체별 커스터마이징 지원 (별명, 메모, 태그 등)',
            '### 성능 최적화',
            '대기시간 단축하기 위해 Promise.all 로 독립 쿼리 병렬 처리',
            '트랜잭션 활용으로 데이터 일관성 유지 및 롤백 처리',
            '### 에러 모니터링',
            'Sentry 웹훅 수신 → ClickUp API로 자동 태스크 생성',
            '에러 우선순위 자동 할당, 상세 정보(URL, 에러 ID, 에러 메세지 등) 포함',
            '에러 발생 시 뷰에 알림 댓글 자동 등록으로 실시간 알림',
            '에러 발생량 감소 및 평균 복구 시간 개선',
            '### 세밀한 RBAC 권한 관리 시스템',
            '계층 구조: Owner(전체 권한) → Team Leader(부가 권한) → 일반 직원(메뉴별 세부 권한)',
            '메뉴 단위 권한 제어(Read/Create/Update/Delete 분리)',
            'API 미들웨어에서 권한 실시간 검증(assertPermission)',
            '업체별 커스텀 권한 그룹 생성 및 할당',
            '### 데이터 마이그레이션',
            '4개 이상 레거시 시스템(아하소프트, 그루머노트, 티피, 이노펫) 데이터 변환',
            '데이터 매핑 자동화(고객/반려동물/예약 정보 변환)',
            '상태 코드 변환(레거시 → 표준화된 상태 코드)',
            '순차 처리와 API 호출 간 딜레이를 통한 서버 부하 최소화',
            '### drizzle db pull',
            '개발 환경에서 서버 시작 시 자동 스키마 동기화(bun drizzle-kit pull)',
            '스키마 파일 자동 업데이트(mode: \'string\' → mode: \'date\')',
            '컴파일 타임 타입 체크로 런타임 스키마 불일치 방지',
            '개발자 경험 향상 및 스키마 변경 감지'
        ],
        assets: [
        ],
        mainAsset: 0
    }
}

export default projects;