const sideProjects = {
    '자사 브랜딩 사이트': {
        title: '자사 브랜딩 사이트',
        description: '자사 브랜딩 페이지',
        features: [
            '풍부한 애니메이션을 활용한 브랜드 아이덴티티 연출',
            '이미지·영상 에셋 기반의 비주얼 중심 레이아웃 구성'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Vercel',
            'Tailwind CSS',
            'Recoil',
            'GSAP',
            'Fastify',
            'Node.js',
            'AWS Lambda',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-06',
        contribution: [
            '단독 프론트엔드 프로젝트',
            '',
            '프론트엔드 아키텍처 설계',
            '  - Next.js 기반 App Router 기반 프로젝트 설계',
            '  - Recoil 기반 전역 상태 관리 구조',
            '프론트엔드 개발',
            '  - 히어로, 비전, 문화, 포트폴리오, 연혁, 파트너, 인증, 복지, 연락처, 회사정보, 푸터 등 전체 페이지 섹션 개발',
            '  - GSAP scrollTrigger, IntersectionObserver 기반 에니메이션, 반응형 구현',
            '  - 반응형 디자인 구현 (PC/모바일 분기 처리)',
            '  - 커스텀 슬라이더 컴포넌트 구현 (카드 스택 구조)',
            '유지보수 담당',
            '  - 버그 수정 및 추가 개발'
        ],
        totalDeveloper: 1,
        contributedPercentage: 100,
        frontEnd: true,
        backend: false,
        detail: [
            '### 복잡한 UI 에니메이션 구현',
            'GSAP ScrollTrigger 활용한 스크롤 기반 에니메이션',
            '커스텀 슬라이더 컴포넌트- 카드 스택 에니메이션',
            'IntersectionObserver 기반 뷰포트 감지 에니메이션',
            'CSS 트랜지션과 javascript 상태 관리 결합',
            '에니메이션 및 UX 요구사항을 모두 충족하도록 구현',
            '### 디자인 시안에 맞춘 슬라이더 컴포넌트 구현',
            't: 디자인 시안에 맞춘 슬라이더 컴포넌트를 기존 라이브러리로 구현 불가',
            's: 카드 스택 구조와 에니메이션을 직접 구현',
        ],
        assets: [
            `/assets/projects/자사 브랜딩 사이트/1.gif`,
            `/assets/projects/자사 브랜딩 사이트/1.png`,
            `/assets/projects/자사 브랜딩 사이트/2.png`,
            `/assets/projects/자사 브랜딩 사이트/3.png`,
            `/assets/projects/자사 브랜딩 사이트/4.png`,
            `/assets/projects/자사 브랜딩 사이트/5.png`,
        ],
        mainAsset: 1
    },
    라이프커밋: {
        title: '라이프커밋',
        description: '라이프 루틴을 기록하고 시각적으로 관리하며, 건강한 라이프스타일을 만들어갈 수 있는 모바일 앱',
        features: [
            '루틴 버튼 생성 및 커스터마이즈(사이즈, 색상, 아이콘 등)',
            '그리드 기반 루틴 배치 및 위치 조정',
            '루틴 수행 시 버튼 클릭으로 기록 저장',
            '월별/연도별 통계 제공',
            '기록 시각화 및 깃허브 커밋(잔디 심기) 스타일 진행도 표시',
            '앱스토어 및 플레이스토어 출시'
        ],
        skills: [
            'React Native',
            'Expo',
            'EAS',
            'Typescript',
            'Fastify',
            'Node.js',
            'Knex.js',
            'AWS Lambda',
            'AWS RDS',
            'AWS S3'
        ],
        duration: '2024-05 - 2024-06',
        contribution: [
            '솔로 프로젝트',
            '',
            '기획, 디자인, 개발 전 과정 전담',
            '',
            '앱 기획',
            '  - 습관 추적 앱 컨셉 기획, 기능 명세서 작성',
            '  - UI/UX 디자인',
            '  - 블록 위주 디자인',
            '  - 아이폰 배경화면, Github 잔디 레퍼런스 디자인',
            '프론트엔드/백엔드 아키텍처 설계',
            '  - React Native, Expo 기반 구조 설계',
            '  - Fastify 기반 서버 구조 설계',
            '  - AWS Lambda 서버리스 아키텍처 사용',
            '  - MySQL 데이터베이스 설계',
            '프론트엔드 기능 개발',
            '- 블록 관리 시스템',
            '  - 다양한 사이즈 블록 생성/수정/삭제, 커스터마이징',
            '  - 아이폰 배경화면과 유사한 드래그앤드롭 위치 조정 기능',
            '- 일별 습관 기록 기능',
            '- 월별 통계 집계 및 시각화 (캘린더뷰/통계뷰)',
            '- 프로필 관리 기능',
            '- 휴대폰 번호 기반 사용자 인증 체계',
            '  - 휴대폰 인증번호 발송 및 검증',
            '  - JWT 기반 로그인'
        ],
        totalDeveloper: 1,
        contributedPercentage: 100,
        frontEnd: true,
        backend: true,
        detail: [
            '### 단계별 블록 생성 기능',
            '크기 선택 → 색상 선택 → 아이콘 선택 → 텍스트 입력 의 4단계 에니메이션 전환',
            '단계별 진행 상태 표시',
            '### 드래그앤드롭 기반 블록 위치 변경 기능 구현',
            '4x4 그리드의 빈 자리에 생성된 블록 자동 배치',
            '원하는 위치로 드래그앤드롭으로 블록 이동',
            '블록간 겹침/경계 체크하여 유효할 경우에는 이동, 이외에는 복귀',
            '터치 이벤트 핸들러로, 터치 좌표와 블록 위치 계산하여 자연스러운 드래그앤드롭 구현',
            '### 구글 Ads 연동 수익화'
        ],
        assets: [
            `/assets/projects/라이프커밋/1.png`,
            `/assets/projects/라이프커밋/2.png`,
            `/assets/projects/라이프커밋/3.png`,
            `/assets/projects/라이프커밋/4.png`,
            `/assets/projects/라이프커밋/5.png`,
            `/assets/projects/라이프커밋/6.png`,
            `/assets/projects/라이프커밋/7.png`,
        ],
        mainAsset: 0
    },
    '주유기록 인앱토스': {
        title: '주유기록 인앱토스',
        description: '주유 기록과 연비, 주행거리를 관리할 수 있는 모바일 앱',
        features: [
            '차량 다중 등록 및 관리',
            '차량별 주유 기록 작성',
            '마지막 주유 기록 기반 연비 및 주행거리 자동 계산',
            '월별/연도별 주유·연비 통계 제공',
            '(토스 정책 이슈로 미출시)'
        ],
        skills: [
            'React',
            'Vite',
            'Typescript',
            'Tailwind CSS',
            'Fastify',
            'Node.js',
            'MySQL',
            'Knex.js',
            'AWS RDS',
            'AWS Lambda',
            'AWS S3',
            'Swagger'
        ],
        duration: '2025-10-31 - 2024-11-05',
        contribution: [
            '프론트엔드 아키텍처 설계 참여',
            '- React/Vite 기반 프론트엔드 구조 설계',
            '- Granite.js 프레임워크 적용',
            '- Context APi 활용 전역 상태 관리',
            '프론트엔드/백엔드 2개 주요 기능 UI 및 API 개발 (팀 내 기여도 70%)',
            '- 차량 관리',
            '  - 차량 등록/수정/삭제/조회',
            '  - 다중 차량 관리 및 전환 기능',
            '- 주유기록 관리',
            '  - 주유기록 작성/수정/삭제',
            '  - 지난 주유기록 바탕으로 연비/주유량/주행거리 자동 계산',
            '  - 연도/월별 기록 조회',
            '- 통계',
            '  - 연비/주유횟수/금액/주행거리 등 월별/연도별 통계 및 증감 표시'
        ],
        totalDeveloper: 1,
        contributedPercentage: 100,
        frontEnd: true,
        backend: true,
        detail: [
            '### 자동 토큰 갱신 및 재시도 로직',
            '401 에러 감지 시 refresh token으로 자동 갱신',
            '토큰 갱신 성공 시 실패한 요청 자동 재시도',
            'code',
            '### 커스텀 훅 패턴으로 비즈니스 로직 분리 및 아키텍처 개선',
            '각 도메인 별 커스텀 훅으로 비즈니스 로직 분기',
            '- useApi',
            '  - openapi 기반 API 호출',
            '  - 자동 토큰 갱신 및 재시도',
            '  - snake/camel 케이스 자동 변환',
            '  - 로딩/에러 상태 관리',
            '- useVehicle',
            '  - LocalStorage/Api/State 세 곳에서 관리되는 차량 정보 관리 및 동기화',
            '  - 비동기 상태 동기화 및 Race Condition 해결',
            '- useAuth',
            '  - 토스 앱 로그인 연동',
            '  - 토큰 저장 및 복원',
            '  - 세션 유효성 검증',
            '  - 로그아웃 처리',
            '코드 중복제거로 약 500줄 이상의 코드 감소',
            '관리 주체 일원화로 일관성 확보',
            '유지보수성 개선',
            '개발 시간 단축'
        ],
        assets: [
            `/assets/projects/주유기록 인앱토스/1.png`,
            `/assets/projects/주유기록 인앱토스/2.png`,
            `/assets/projects/주유기록 인앱토스/3.png`,
            `/assets/projects/주유기록 인앱토스/4.png`,
            `/assets/projects/주유기록 인앱토스/5.png`,
        ],
        mainAsset: 0
    },
    sjlog: {
        title: 'Sjlog',
        description: '일기, 가계부, 블로그 등 다양한 기록을 효율적으로 작성·관리할 수 있는 통합 서비스',
        features: [
            '일기, 가계부 등 항목별 맞춤 UI 제공',
            '블로그 글 작성 및 관리: 폴더 구조 + 자동 저장 에디터(blockNote)',
            '기록의 효율적 저장 및 조회 지원'
        ],
        skills: [
            'Next.js',
            'React',
            'Typescript',
            'Tailwind CSS',
            'Mui',
            'Radix UI',
            'React Query',
            'Supabase',
            'Bun',
            'Drizzle',
            'PostgreSQL',
            'Supabase Auth'
        ],
        duration: '2025-04 - 2025-12',
        contribution: [
            '개인 프로젝트',
            '',
            '프론트엔드/백엔드 아키텍처 설계',
            '- Next.js App Router 기반 풀스택 아키텍처',
            '- Server Actions 패턴을 활용한 API',
            '- Supabase (PostgresSQL + Auth) 기반 DB 스키마 설계',
            '- Drizzle ORM 활용 타입 안정성 확보',
            '프론트엔드/백엔드 UI 및 API 개발',
            '- 인증/세션 관리: Supabase Auth 연동, JWT 토큰 자동 갱신 미들웨어',
            '- 일기, 개발 로그, 금융 등 기록 기능'
        ],
        totalDeveloper: 1,
        contributedPercentage: 100,
        frontEnd: true,
        backend: true,
        detail: [
            '### Server Component + Server Actions 패턴',
            '소규모 프로젝트에서 개발시간을 단축하고 일관된 타입 적용하기 위해 적용',
            '서버 컴포넌트에서 초기 데이터 로드하여 클라이언트 컴포넌트에 props로 전달하는 패턴 적용',
            '로딩 속도 단축 및 UX 개선',
            '별도 API 라우트 없이 타입 안정성 갖춘 서버 로직 구축',
            '### BlockNote 기반 상세조회 및 에디터 기능 통합',
            'JSON 기반 블록 데이터 구조 관리: BlockNote의 블록 데이터를 JSON 문자열로 저장하고 파싱하여 에디터 상태와 동기화',
            '불필요한 리렌더링 방지: JSON.stringify 비교를 통해 변경된 경우에만 상태 업데이트하여 성능 최적화',
            '동적 블록 교체 로직: 선택된 로그 변경 시 기존 블록을 삭제한 후 새 블록을 삽입하는 방식으로 메모리 누수 방지 및 에디터 상태 초기화',
            '자동 저장 기능: 2초 debounce를 적용하여 사용자 입력 중단 시 자동으로 저장하여 데이터 손실 방지',
            '헤딩 블록 기반 목차 자동 생성: 에디터 내 헤딩 블록을 추출하여 사이드바에 목차를 동적으로 표시',
            '### DB 스키마 자동 타입 생성 로직',
            'Drizzle ORM 스키마 기반 타입 생성: drizzle-kit pull로 데이터베이스 스키마를 가져온 후, InferSelectModel을 활용하여 TypeScript 타입 자동 생성',
            '스크립트 기반 자동화: createTypesFromSchema.ts 스크립트를 통해 스키마 변경 시 자동으로 타입 파일(types/schemaType.ts) 생성',
            '타입 안전성 확보: 데이터베이스 스키마와 TypeScript 타입을 동기화하여 런타임 오류 방지 및 개발 생산성 향상',
            'Omit을 활용하여 pk, createdAt, updatedAt, uid 같은 내부 필드는 필수 타입에서 제외.',
            '### Middleware 활용한 JWT 토큰 자동 갱신 미들웨어',
            '초기 데이터 패치시, 서버 컴포넌트에서 호출한 서버 액션은 쿠키에 접근할 수 없는 문제',
            '미들웨어에서 Server Action(checkSession)을 직접 호출하여 토큰 검증 및 자동 갱신 로직 구현함으로서 해결',
            '토큰 만료 시 자동 갱신: checkSession 내부에서 토큰 검증 실패 시 자동으로 refresh token을 사용해 새 토큰 발급',
            '별도의 API 라우트 핸들러 구현 없이 미들웨어 레벨에서 인증 처리하여 코드 중복 제거'
        ],
        assets: [
            `/assets/projects/sjlog/1.png`,
        ],
        mainAsset: 0
    }
}

export default sideProjects;